name: SonarCloud [Main]
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest  # Substitua por sua imagem de banco de dados, se for diferente
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: teste-jpa
        options: >-
          --health-cmd="pg_isready -U testuser" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          
          
      - name: Create dotenv File
        run: |
          touch /home/runner/work/CRUD-event/CRUD-event/.env
          echo DB_URL_DEFAULT="jdbc:postgresql://localhost:5432/default" >> /home/runner/work/CRUD-event/CRUD-event/.env
          echo DB_URL_TEST="jdbc:postgresql://localhost:5432/teste-jpa" >> /home/runner/work/CRUD-event/CRUD-event/.env
          echo DB_DRIVER="org.postgresql.Driver" >> /home/runner/work/CRUD-event/CRUD-event/.env
          echo DB_USER="testuser" >> /home/runner/work/CRUD-event/CRUD-event/.env
          echo DB_PASSWORD="testpassword" >> /home/runner/work/CRUD-event/CRUD-event/.env
          cat /home/runner/work/CRUD-event/CRUD-event/.env
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=camilajullyane_CRUD-event
