name: Package

on:
  workflow_run:
    workflows: ["maven"]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build and package with Maven
      run: mvn package

    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
        name: my-jar-file
        path: target/*.jar
