name: release package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all
    name: Build and Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
          
    - name: Create dotenv File
      run: |
        touch /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_URL_DEFAULT="${{ secrets.DB_URL_DEFAULT }}" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_URL_TEST="${{ secrets.DB_URL_TEST }}" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_DRIVER="${{ secrets.DB_DRIVER }}" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_USER="${{ secrets.DB_USER }}" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> /home/runner/work/CRUD-event/CRUD-event/.env
        cat /home/runner/work/CRUD-event/CRUD-event/.env
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
