name: release package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    services:
      db:
        image: postgres:latest  # Substitua por sua imagem de banco de dados, se for diferente
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: teste-jpa
        options: >-
          --health-cmd="pg_isready -U testuser" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    name: Build and Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
          
    - name: Create dotenv File
      run: |
        touch /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_URL_DEFAULT="jdbc:postgresql://localhost:5432/default" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_URL_TEST="jdbc:postgresql://localhost:5432/teste-jpa" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_DRIVER="org.postgresql.Driver" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_USER="testuser" >> /home/runner/work/CRUD-event/CRUD-event/.env
        echo DB_PASSWORD="testpassword" >> /home/runner/work/CRUD-event/CRUD-event/.env
        cat /home/runner/work/CRUD-event/CRUD-event/.env
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

