name: release package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all
    name: Build and Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
          
    - name: Create dotenv File
      run: |
        $envPath = "C:\path\to\CRUD-event\.env"
        if (!(Test-Path $envPath)) {
            New-Item -ItemType File -Path $envPath | Out-Null
        }
        
        # Adiciona as variáveis ao arquivo .env
        Add-Content -Path $envPath -Value "DB_URL_DEFAULT=${{ secrets.DB_URL_DEFAULT }}"
        Add-Content -Path $envPath -Value "DB_URL_TEST="${{ secrets.DB_URL_TEST }}"
        Add-Content -Path $envPath -Value "DB_DRIVER=${{ secrets.DB_DRIVER }}"
        Add-Content -Path $envPath -Value "DB_USER=${{ secrets.DB_USER }}"
        Add-Content -Path $envPath -Value "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        Get-Content -Path $envPath
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
